// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmsMaster.Data;

namespace SmsMaster.Data.Migrations
{
    [DbContext(typeof(SmsMasterContext))]
    partial class SmsMasterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SmsMaster.Model.Country", b =>
                {
                    b.Property<string>("MobileCountryCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("PricePerSms")
                        .HasColumnType("decimal(6, 3)");

                    b.HasKey("MobileCountryCode");

                    b.ToTable("Country");

                    b.HasData(
                        new { MobileCountryCode = "262", CountryCode = "49", Name = "Germany", PricePerSms = 0.055m },
                        new { MobileCountryCode = "232", CountryCode = "43", Name = "Austria", PricePerSms = 0.053m },
                        new { MobileCountryCode = "260", CountryCode = "48", Name = "Poland", PricePerSms = 0.032m }
                    );
                });

            modelBuilder.Entity("SmsMaster.Model.Sms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("From")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Mcc")
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6, 3)");

                    b.Property<int>("State");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("To")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Sms");
                });
#pragma warning restore 612, 618
        }
    }
}
